name: integration
on:
  push:
    tags:
      - v*
    branches:
      - main
      - release-*
      - ci-*
  pull_request:
env:
  GO_VERSION: '1.20'
permissions:
  contents: read

jobs:
  test-cgroupfs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: go-integration-v1-${{ hashFiles('**/go.sum') }}
          restore-keys: go-integration-v1-
      - run: scripts/github-actions-packages
      - run: scripts/github-actions-setup
      - run: make all test-binaries
      - run: sed -i 's/\.slice//g' test/testdata/*.json
      - run: sudo -E CONTAINER_CGROUP_MANAGER=cgroupfs CONTAINER_CONMON_CGROUP=pod JOBS=1 bats --verbose-run test/workloads.bats -f "test infra ctr cpuset"
      - run: sudo -E CONTAINER_CGROUP_MANAGER=cgroupfs CONTAINER_CONMON_CGROUP=pod JOBS=1 bats --verbose-run test/workloads.bats -f "test workload gets configured to defaults"
      - run: sudo -E CONTAINER_CGROUP_MANAGER=cgroupfs CONTAINER_CONMON_CGROUP=pod JOBS=1 bats --verbose-run test/workloads.bats -f "test workload can override defaults"
      - run: sudo -E CONTAINER_CGROUP_MANAGER=cgroupfs CONTAINER_CONMON_CGROUP=pod JOBS=1 bats --verbose-run test/workloads.bats -f "test workload should not be set if not defaulted or specified"
      - run: sudo -E CONTAINER_CGROUP_MANAGER=cgroupfs CONTAINER_CONMON_CGROUP=pod JOBS=1 bats --verbose-run test/workloads.bats -f "test workload pod gets configured to defaults"
      - run: sudo -E CONTAINER_CGROUP_MANAGER=cgroupfs CONTAINER_CONMON_CGROUP=pod JOBS=1 bats --verbose-run test/workloads.bats -f "test workload can override pod defaults"
      - run: sudo -E CONTAINER_CGROUP_MANAGER=cgroupfs CONTAINER_CONMON_CGROUP=pod JOBS=1 bats --verbose-run test/workloads.bats -f "test workload pod should not be set if not defaulted or specified"
      - run: sudo -E CONTAINER_CGROUP_MANAGER=cgroupfs CONTAINER_CONMON_CGROUP=pod JOBS=1 bats --verbose-run test/workloads.bats -f "test workload pod should not be set if annotation not specified"
      - run: sudo -E CONTAINER_CGROUP_MANAGER=cgroupfs CONTAINER_CONMON_CGROUP=pod JOBS=1 bats --verbose-run test/workloads.bats -f "test workload pod should override infra_ctr_cpuset option"
